name: Terraform Pull Request

permissions:
  contents: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.tf"

jobs:
  format:
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-format.yaml@main
    secrets: inherit
  validate:
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-validate.yaml@main
    secrets: inherit
  plan:
    needs: [format, validate]
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-plan.yaml@main
    secrets: inherit
