name: Pull Request Validation

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    paths:
      - "**.tf"

jobs:
  docs:
    name: Terraform Docs
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-docs.yaml@main
  format:
    name: Terraform Format
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-format.yaml@main
  lint:
    name: Terraform Lint
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-lint.yaml@main
  validate:
    name: Terraform Validate
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-validate.yaml@main
  plan:
    name: Terraform Plan
    needs:
      - format
      - validate
    uses: SoliDeoGloria-Tech/workflow-testing/.github/workflows/terraform-plan.yaml@main
    secrets: inherit
