on:
  workflow_call:
    inputs:
      terraform-version:
        description: Terraform version to use
        type: string
        required: false
        default: latest
      runs-on:
        description: Runner to use
        type: string
        required: false
        default: "['ubuntu-latest']"

env:
  TF_IN_AUTOMATION: true

jobs:
  format:
    name: Correct Formatting
    runs-on: ${{ fromJson(inputs.runs-on) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ inputs.terraform-version }}

      - name: Terraform Format
        run: terraform fmt

      - name: Post Suggested Changes
        uses: parkerbxyz/suggest-changes@v1
        with:
          comment: Please correct the Terraform formatting
