name: Terraform Documentation

permissions:
  contents: read

on:
  workflow_call:

jobs:
  verify:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install terraform-docs
        run: |
          curl -Lo ./terraform-docs.tar.gz https://github.com/terraform-docs/terraform-docs/releases/download/v0.17.0/terraform-docs-v0.17.0-$(uname)-amd64.tar.gz
          tar -xzf terraform-docs.tar.gz
          chmod +x terraform-docs
          mv terraform-docs /usr/local/bin/terraform-docs

      - name: Generate Docs
        run: |
          terraform-docs . --recursive
          if [ $(git_status) -ne 0 ]; then
            echo "::error ::Uncommitted change(s) has been found!"
            exit 1
          fi
