name: Terraform Format

permissions:
  contents: read

on:
  workflow_call:

jobs:
  format:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # v3 uses NodeJS 20

      - name: Terraform Format
        run: terraform fmt -check -recursive
