name: Terraform Documentation

permissions:
  contents: read

on:
  workflow_call:

jobs:
  verify:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Docs
        uses: terraform-docs/gh-actions@v1.1.0
        with:
          fail-on-diff: true
          recursive: true
