name: Terraform Validate

permissions:
  contents: read

on:
  pull_request:
    types: ["opened", "synchronize"]
    paths:
      - "**.tf"

jobs:
  validate:
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2 # v3 uses NodeJS 20

      - name: Terraform Init
        run: terraform init -backend=false

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
